FROM biggates/uvicorn-gunicorn-fastapi-science:python3.8
WORKDIR .
COPY . .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

ENV PYTHONUNBUFFERED 1

# Running the consumer to get the data
CMD ["python", "monitoring/online_evaluation.py"]